apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cryptoscope
  labels:
    app: frontend
    project: cryptoscope
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
